# Generated by Django 4.1.7 on 2023-05-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclingcenter',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
