# Generated by Django 4.1.7 on 2023-05-12 05:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand_product', '0001_initial'),
        ('recycling_center', '0002_recyclingcenter_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrecycled',
            name='brand',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='brand_product.brand_product'),
            preserve_default=False,
        ),
    ]
