# Generated by Django 4.1.7 on 2023-06-12 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_is_customer'),
        ('recycling_center', '0004_alter_itemrecycled_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrecycled',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.brands'),
        ),
    ]
