# Generated by Django 4.1.7 on 2023-06-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness_plan_metrics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awarenessplanmetrics',
            name='impacted',
        ),
        migrations.RemoveField(
            model_name='awarenessplanmetrics',
            name='proposed',
        ),
        migrations.AddField(
            model_name='awarenessplanmetrics',
            name='number_of_life_touched',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='awarenessplanmetrics',
            name='number_of_themes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='awarenessplanmetrics',
            name='targeted_demographics',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='awarenessplanmetrics',
            name='targeted_interest',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='awarenessplanmetrics',
            name='total_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
