# Generated by Django 4.1.7 on 2023-04-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('brand', 'Brand'), ('refurbisher', 'Refurbisher'), ('collection_center', 'Collection_Center'), ('recycling_unit', 'Recycling_Unit'), ('individual_consumer', 'Individual_Consumer'), ('bulk_consumer', 'Bulk_Consumer')], default='brand', max_length=20),
        ),
    ]
