# Generated by Django 4.1.7 on 2023-05-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('brand', 'Brand'), ('refurbisher', 'Refurbisher'), ('collection_center', 'Collection Center'), ('recycling_unit', 'Recycling Unit'), ('individual_consumer', 'Individual Consumer'), ('bulk_consumer', 'Bulk Consumer')], default='brand', max_length=20),
        ),
    ]
