# Generated by Django 4.1.7 on 2023-05-10 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awarenessplan',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 10, 9, 47, 59, 569389, tzinfo=datetime.timezone.utc)),
        ),
    ]
