# Generated by Django 4.1.7 on 2023-05-10 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('awareness_plan', '0002_alter_awarenessplan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awarenessplan',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
