# Generated by Django 4.1.7 on 2023-05-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness_plan', '0003_alter_awarenessplan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awarenessplan',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
