# Generated by Django 4.1.7 on 2023-05-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness_plan', '0004_alter_awarenessplan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awarenessplan',
            name='medium',
            field=models.CharField(choices=[('school_program', 'School Program'), ('polular_places_program', 'Popular Places Program'), ('awareness_drive', 'Awareness Drive'), ('advertisements', 'Advertisements'), ('online_campaigns', 'Online Campaigns')], default='online_campaigns', max_length=50),
        ),
    ]
