# Generated by Django 4.1.7 on 2023-05-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness_plan', '0005_alter_awarenessplan_medium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awarenessplan',
            name='medium',
            field=models.CharField(choices=[('school_program', 'School Program'), ('polular_places_program', 'Popular Places Program'), ('awareness_drive', 'Awareness Drive'), ('advertisements', 'Advertisements'), ('online_campaigns', 'Online Campaigns'), ('city_awareness_and_collection_drive', 'City Awareness and Collection Drive'), ('radios', 'Radios'), ('rwas', 'RWAs')], default='online_campaigns', max_length=50),
        ),
    ]
