# Generated by Django 4.1.7 on 2023-05-15 19:28

import awareness_plan.models
from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('awareness_plan', '0007_awarenessplan_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awarenessplan',
            name='medium',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('school_program', 'School Program'), ('polular_places_program', 'Popular Places Program'), ('awareness_drive', 'Awareness Drive'), ('advertisements', 'Advertisements'), ('online_campaigns', 'Online Campaigns'), ('city_awareness_and_collection_drive', 'City Awareness and Collection Drive'), ('radios', 'Radios'), ('rwas', 'RWAs')], default=['online_campaigns'], max_length=133, validators=[awareness_plan.models.validate_medium_count]),
        ),
    ]
