# Generated by Django 4.1.7 on 2023-06-06 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_role'),
        ('awareness_plan', '0008_alter_awarenessplan_medium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awarenessplan',
            name='product',
        ),
        migrations.AddField(
            model_name='awarenessplan',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='awarenessplan',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.brands'),
        ),
        migrations.AlterField(
            model_name='awarenessplan',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='awarenessplan',
            name='theme',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
