# Generated by Django 4.1.7 on 2023-05-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_center', '0002_alter_collectioncenter_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioncenter',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
