# Generated by Django 4.1.7 on 2023-06-11 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_center', '0003_alter_collectioncenter_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectedCenterItemCollected',
        ),
    ]
