# Generated by Django 4.1.7 on 2023-05-05 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Item_collected', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcollected',
            options={},
        ),
        migrations.AlterModelTable(
            name='itemcollected',
            table='ItemCollected',
        ),
    ]
