# Generated by Django 4.1.7 on 2023-05-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item_collected', '0003_itemcollected_brand_itemcollected_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcollected',
            name='target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemcollected',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
