# Generated by Django 4.1.7 on 2023-06-11 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_is_customer'),
        ('collection_center', '0004_delete_collectedcenteritemcollected'),
        ('Item_collected', '0004_alter_itemcollected_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcollected',
            name='collectioncenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collection_center.collectioncenter'),
        ),
        migrations.AlterField(
            model_name='itemcollected',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.brands'),
        ),
    ]
